import {
  LayoutDashboard,
  UserPlus,
  Contact,
  Building2,
  Handshake,
  Activity,
  GitBranch,
  Package,
  FileText,
  ShoppingCart,
  Receipt,
  Megaphone,
  Mail,
  MessageSquare,
  Headphones,
  Ticket,
  Inbox,
  MessageCircle,
  BookOpen,
  FolderKanban,
  BarChart3,
  Zap,
  Plug,
  Settings,
  Users,
  Shield,
  ShieldCheck,
  CreditCard,
  User,
  Layers,
  SlidersHorizontal,
  Database,
} from 'lucide-react';

/** PRD-aligned sidebar navigation */
export const NAV_SECTIONS = [
  {
    label: null,
    items: [{ href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard }],
  },
  {
    label: 'CRM',
    items: [
      { href: '/crm/leads', label: 'Leads', icon: UserPlus },
      { href: '/crm/contacts', label: 'Contacts', icon: Contact },
      { href: '/crm/companies', label: 'Accounts', icon: Building2 },
      { href: '/crm/deals', label: 'Opportunities', icon: Handshake },
      { href: '/crm/activities', label: 'Activities', icon: Activity },
    ],
  },
  {
    label: 'Sales',
    items: [
      { href: '/sales/pipeline', label: 'Pipeline', icon: GitBranch },
      { href: '/sales/products', label: 'Products', icon: Package },
      { href: '/sales/quotations', label: 'Quotations', icon: FileText },
      { href: '/sales/orders', label: 'Orders', icon: ShoppingCart },
      { href: '/sales/invoices', label: 'Invoices', icon: Receipt },
    ],
  },
  {
    label: 'Marketing',
    items: [
      { href: '/marketing/campaigns', label: 'Campaigns', icon: Megaphone },
      { href: '/massmail', label: 'Email Marketing', icon: Mail },
      { href: '/marketing/sms', label: 'SMS Marketing', icon: MessageSquare },
    ],
  },
  {
    label: 'Customer Service',
    items: [
      { href: '/service/tickets', label: 'Tickets', icon: Ticket },
      { href: '/service/queues', label: 'Queues', icon: Inbox },
      { href: '/service/macros', label: 'Macros', icon: MessageCircle },
      { href: '/service/chat', label: 'Live Chat', icon: Headphones },
      { href: '/service/knowledge', label: 'Knowledge Base', icon: BookOpen },
    ],
  },
  {
    label: 'Work',
    items: [
      { href: '/projects', label: 'Projects', icon: FolderKanban },
      { href: '/tasks', label: 'Tasks', icon: Activity },
      { href: '/reports', label: 'Reports', icon: BarChart3, action: 'read', subject: 'Analytics' },
      { href: '/automation', label: 'Automation', icon: Zap },
      { href: '/integrations', label: 'Integrations', icon: Plug },
    ],
  },
  {
    label: 'Workspace',
    items: [
      { href: '/settings/profile', label: 'Profile', icon: User },
      { href: '/settings/tenant', label: 'Organization', icon: Building2, action: 'manage', subject: 'Settings' },
      { href: '/settings/users', label: 'Team', icon: Users, action: 'manage', subject: 'User' },
      { href: '/settings/departments', label: 'Departments', icon: Layers, action: 'manage', subject: 'Department' },
      { href: '/settings/roles', label: 'Roles', icon: Shield, action: 'manage', subject: 'Group' },
      { href: '/settings/lead-routing', label: 'Lead Routing', icon: GitBranch, action: 'manage', subject: 'Settings' },
      { href: '/settings/pipelines', label: 'Pipelines', icon: GitBranch, action: 'manage', subject: 'Settings' },
      { href: '/settings/custom-fields', label: 'Custom Fields', icon: SlidersHorizontal, action: 'manage', subject: 'Settings' },
      { href: '/settings/audit', label: 'Security & Audit', icon: ShieldCheck, action: 'manage', subject: 'Settings' },
      { href: '/settings/data-jobs', label: 'Data Jobs', icon: Database, action: 'manage', subject: 'Settings' },
      { href: '/settings/billing', label: 'Billing', icon: CreditCard, action: 'manage', subject: 'Settings' },
      { href: '/settings', label: 'Settings', icon: Settings },
    ],
  },
];
